package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type AutoGenerated struct {
	Success bool `json:"success"`
	Details struct {
		ID           string `json:"id"`
		ClientID     string `json:"client_id"`
		ProductID    string `json:"product_id"`
		ExtraDetails struct {
			Orgname string `json:"orgname"`
			Vdcref  string `json:"vdcref"`
			OrgID   string `json:"org_id"`
			VdcID   string `json:"vdc_id"`
		} `json:"extra_details"`
	}
}

func hbAccDetTaker(sliceAcc []string) map[string]string {

	var accID string
	accMap := make(map[string]string)
	for i := range sliceAcc {
		accID = sliceAcc[i]

		res, err := http.Get("http://prodportal.kazteleport.kz/admin/api.php?api_id=ea91342f6734cc993eb2&api_key=f3175b6ab1c9c138d1d5&call=getAccountDetails&id=" + accID)
		if err != nil {
			fmt.Println(err)
		}
		body, err := io.ReadAll(res.Body)
		if err != nil {
			fmt.Println(err)
		}
		var hbAccount AutoGenerated
		json.Unmarshal(body, &hbAccount)

		accMap[sliceAcc[i]] = hbAccount.Details.ExtraDetails.VdcID
	}
	return accMap
}
